pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/onboarding-3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${SCRIPTS_PATH}") {
                    sh """
                    echo "Build"
                    """
                    sh "npm install -g yarn"
                    sh "./install.sh"
                    sh "./application-management.sh build"
                    sh "./application-management.sh start"
                }
            }
        }
        stage('Testing') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Testing"
                    """
                    sh "cd ../e2e-web && yarn test"
                }
            }
        }
        stage('Close') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Close"
                    """
                }
                sh "./application-management.sh close"
            }
        }
    }
}