pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/onboarding-3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${PROJECT_PATH}") {
                    sh """
                    echo "install"
                    """
                    sh "cd ./web && npm install"
                    sh "cd ./e2e-web && npm install"
                }
            }
        }
        stage('Build') {
           steps {
                dir("${PROJECT_PATH}/web") {
                    sh """
                    echo "Build"
                    """
                    sh "npm run start &&"
                    // sh "./application-management.sh build"
                    // sh "./application-management.sh start &&"
                }
            }
        }
        stage('Testing') {
            steps {
                dir("${PROJECT_PATH}/e2e-web") {
                   sh """
                    echo "Testing"
                    """
                    sh "npm run test"
                }
            }
        }
        stage('Close') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Close"
                    """
                }
                sh "./application-management.sh close"
            }
        }
    }
}