pipeline {
    agent any

    environment {
        E2E_MODE = "ci"
        DEV = "dev"
        ALPHA = "alpha"
        PREPROD = "preprod"
    }

    parameters {
        string(name: 'VERSION', description: 'The commit target to build.', defaultValue: 'latest')
        booleanParam(name: 'ENABLE_CONTRACT_TEST', description: 'Enable contract testing (will remove this after contract is updated)', defaultValue: false)
        
    }

    stages {
        stage('Build') {
            steps {
                sh """
                echo 'Building..${DEV}'
                """
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                sh """
                echo 'Deploying....${params.VERSION}'
                """
            }
        }
    }
}